services:
  configurator:
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      ${DB_HOST}:
        condition: service_healthy

  ${DB_HOST}:
    image: mariadb:10.6
    container_name: ${DB_HOST}
    healthcheck:
      test: mysqladmin ping -h localhost --password=${MYSQL_ROOT_PASSWORD}
      interval: 1s
      retries: 20
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?No db password set}
    restart: unless_stopped
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
